---

name: FTs
on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:

  review-app-status-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Review App status
        uses: niteoweb/reviewapps-deploy-status@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  functional-tests:
    name: ${{ matrix.os }} FTs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: js, html-report, screenshot

      - name: FTs
        env:
          WEB_URL: ${{ secrets.WEB_URL }}
        run: |
          cd functional-tests
          npm install
          gauge run

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ft-logs-${{ matrix.os }}
          path: functional-tests/logs
