---

name: FTs on pull requests
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:

  functional-tests:
    name: Pull request FTs
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: js, html-report, screenshot

      - name: Verify Review App status
        id: review_app_status
        uses: niteoweb/reviewapps-deploy-status@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PETSTORE_URL output var
        id: set-petstore-url-output-var
        run: |
          CONTRACT_REPO=https://github.com/agilepathway/available-pets-consumer-contract
          CONTRACT_BRANCH=${GITHUB_HEAD_REF}
          if ! git ls-remote --exit-code --heads $CONTRACT_REPO ${CONTRACT_BRANCH}; then
            CONTRACT_BRANCH=master
          fi
          MOCK_SERVER_BASE_URL=https://stoplight.io/mocks/agilepathway/available-pets-consumer-contract
          MOCK_SERVER_ID=84330
          PETSTORE_URL=${{ format('{0}:{1}/{2}/', '$MOCK_SERVER_BASE_URL', '${CONTRACT_BRANCH}', '${MOCK_SERVER_ID}') }}
          echo "::set-output name=petstore-url::${PETSTORE_URL}"
          echo "::set-output name=contract-branch::${CONTRACT_BRANCH}"

      - name: Set PETSTORE_URL config var on Heroku
        run: |
          heroku config:set \
            PETSTORE_URL="${{ steps.set-petstore-url-output-var.outputs.petstore-url }}" \
            --app ${{ steps.review_app_status.outputs.review_app_name }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: FTs
        env:
          WEB_URL: ${{ steps.review_app_status.outputs.review_app_url }}
        run: |
          cd functional-tests
          npm install
          gauge run

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: pull-request-fts-logs
          path: functional-tests/logs

      - name: Fail the build if the contract repo has the same branch as our PR
        if: ${{ steps.set-petstore-url-output-var.outputs.contract-branch != 'master' }}
        uses: actions/github-script@v5
        with:
          script: >
            core.setFailed("
            Our workflow demands that the branch
            ${{ steps.set-petstore-url-output-var.outputs.contract-branch }}
            must not exist on the contract repo - as when it does exist the review app uses it instead of the contract
            repo's master branch, whereas we need the review app to use the master branch before we can merge this pull
            request on our consuming app. Merge the contract repo's branch and then delete it - or just delete it if no
            changes to the contract are required for this consumer feature - then try again.
            ")
