---

name: FTs on pull requests
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:

  functional-tests:
    name: Pull request FTs
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: js, html-report, screenshot

      - name: Verify Review App status
        id: review_app_status
        uses: niteoweb/reviewapps-deploy-status@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: FTs
        env:
          WEB_URL: ${{ steps.review_app_status.outputs.review_app_url }}
        run: |
          cd functional-tests
          npm install
          gauge run

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: pull-request-fts-logs
          path: functional-tests/logs
