---
name: Trunk pipeline to production

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

jobs:

  deploy-to-pre-production:
    runs-on: ubuntu-20.04
    environment: pre-production
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: js, html-report, screenshot

      - name: Pre-production FTs
        env:
          WEB_URL: ${{ secrets.WEB_URL }}
        run: |
          cd functional-tests
          npm install
          gauge run

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: pre-production-fts-logs
          path: functional-tests/logs

  deploy-to-production:
    needs: deploy-to-pre-production
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: js, html-report, screenshot

      - name: Production FTs
        env:
          WEB_URL: ${{ secrets.WEB_URL }}
        run: |
          cd functional-tests
          npm install
          gauge run

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: production-fts-logs
          path: functional-tests/logs
